#!/usr/bin/env node

"use strict";

const fs = require('fs');
const express = require('express');
const app = express();

app.get(/./, function handler(req, res) {
	if (req.path === '/') path = '/index.js';
	else path = req.path;
	if(path.includes("..") || path.includes("~")) return res.status(503).end("Y U HAX >:( ")
	fs.readFile(__dirname + path, function(err, data) {
		if(err) {
			if(process.env.NODE_ENV !== 'production') {
				res.write(err.message + " " + err.stack);
			}
			res.status(500).end();
			return; 
		}
		Function('echo', data)((...args) => res.write(...args));	
		res.end();
	});
	var path;
});

app.listen(8080);
